-- Per-tier compaction toggles + calm-but-severe message copy on tenant_settings.
--
-- Two additive changes:
--   1. Three BOOLEAN columns gate which budget-ladder tier ALSO triggers a
--      context compaction (warn / escalate / final). The default policy is
--      {warn:false, escalate:true, final:true}: compaction at the EARLIEST
--      tier is disabled because the lossy collapse interrupts the worker
--      mid-flight and forces a re-read/re-derive (itself more tool calls and
--      more re-sent context). These mirror the budget-JSON `compact_tiers`
--      key that parseBudgetSpec already honors at dispatch, so the Settings
--      API and per-worker budget overrides stay in sync.
--   2. The twelve budget_*_msg_* DEFAULTs are updated to the calm-but-severe
--      copy that names the driver (re-sent context), explains WHY the worker
--      is near its budget, and gives the concrete remedy (batch tool calls
--      into one round-trip / stop re-reading / deliver the minimal delta).
--      Existing rows are updated ONLY where they still hold the old panicked
--      default (an operator's customized message is left untouched); new rows
--      inherit the new copy via ALTER ... SET DEFAULT.
--
-- Forward-only. Additive-only (no destructive DDL). Compaction policy is now
-- an explicit operator decision at both the tenant default and per-worker
-- levels, not a hidden side effect of crossing a spend threshold.

ALTER TABLE tenant_settings
  ADD COLUMN IF NOT EXISTS budget_compact_warn_tier BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS budget_compact_escalate_tier BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS budget_compact_final_tier BOOLEAN NOT NULL DEFAULT true;

-- New message defaults (applies to rows created from here on).
ALTER TABLE tenant_settings
  ALTER COLUMN budget_warn_msg_tokens SET DEFAULT $$You have used {pct}% of your token budget. This is driven almost entirely by re-sending accumulated context on every turn, not by the work itself. You still have room — just be deliberate from here: batch ALL remaining reads into ONE round-trip, never re-read a file already in context, keep your todo tight, and deliver only the minimal delta. Do that and you'll finish comfortably.$$,
  ALTER COLUMN budget_escalate_msg_tokens SET DEFAULT $$You have used {pct}% of your token budget, and the burn is still from re-sending context each turn. It's recoverable, but it needs a course-correction now rather than later: consolidate every remaining tool call into a single batch, stop re-reading or re-exploring, stick to the todo list, and deliver the deliverable. Re-sending less is what keeps this session alive.$$,
  ALTER COLUMN budget_final_msg_tokens SET DEFAULT $$You have used {pct}% of your token budget — this is the last chance before the session is stopped. Stop all exploration. Finish in the next minimal number of tool calls: batch everything, do not re-read anything already in context, and deliver the completed work now.$$,
  ALTER COLUMN budget_warn_msg_cost_usd SET DEFAULT $$You have used {pct}% of your cost budget. Most of that is re-sent context, not new output. There's room to finish if you act now: batch the remaining tool calls into one round-trip, keep only what the task actually needs in context, and deliver the minimal delta.$$,
  ALTER COLUMN budget_escalate_msg_cost_usd SET DEFAULT $$You have used {pct}% of your cost budget and are on pace to exceed it. Shift to the cheapest path: batch all remaining tool calls, avoid re-deriving anything already established, stick to the todo list, and finish the deliverable now.$$,
  ALTER COLUMN budget_final_msg_cost_usd SET DEFAULT $$You have used {pct}% of your cost budget — this is the final warning. Complete the work in the next few tool calls: batch them and deliver now, or the session will be stopped.$$,
  ALTER COLUMN budget_warn_msg_tool_call_count SET DEFAULT $$You have used {pct}% of your tool-call budget. Splitting work into many separate calls is what's consuming it — every call re-sends the whole conversation. You have room, but please batch here on: combine independent operations into ONE round-trip. Fewer, larger calls finish faster and cost less.$$,
  ALTER COLUMN budget_escalate_msg_tool_call_count SET DEFAULT $$You are at {pct}% of your tool-call budget and still making many small calls. Each one re-sends the whole conversation, which multiplies the cost. Stop the micro calls. Consolidate everything into a single round-trip and focus on completing the todo list.$$,
  ALTER COLUMN budget_final_msg_tool_call_count SET DEFAULT $$You are at {pct}% of your tool-call budget — only a handful of calls remain. Finish in the next tool calls: batch everything into one round-trip, do not re-read, and deliver the completed work now, or the session will be stopped.$$,
  ALTER COLUMN budget_warn_msg_wall_clock_seconds SET DEFAULT $$You have used {pct}% of your time budget. There's still time if you move deliberately from here: batch the remaining tool calls, keep to the todo list, and finish the deliverable.$$,
  ALTER COLUMN budget_escalate_msg_wall_clock_seconds SET DEFAULT $$You have used {pct}% of your time budget. Shift to the fastest path: batch the remaining tool calls, stop re-checking settled state, and finish now.$$,
  ALTER COLUMN budget_final_msg_wall_clock_seconds SET DEFAULT $$You have used {pct}% of your time budget — almost out of time. Complete the work in the next tool calls and deliver now, or the session will be stopped.$$;

-- Roll the new copy onto existing rows that still hold the old default.
-- Each column is updated only where it equals the legacy panicked default, so
-- an operator who customized a message keeps it.
UPDATE tenant_settings SET budget_warn_msg_tokens = $$You have used {pct}% of your token budget. This is driven almost entirely by re-sending accumulated context on every turn, not by the work itself. You still have room — just be deliberate from here: batch ALL remaining reads into ONE round-trip, never re-read a file already in context, keep your todo tight, and deliver only the minimal delta. Do that and you'll finish comfortably.$$ WHERE budget_warn_msg_tokens = $$WARNING: You have used {pct}% of your token budget. STOP and reconsider how you are handling context — you are re-sending too much on every turn. Stick to your todo list and ensure you are moving forward efficiently. Empty your todo, consolidate EVERY remaining read/probe into ONE batched tool call, and deliver only the minimal delta. Reduce context churn immediately or your session will be KILLED.$$;
UPDATE tenant_settings SET budget_escalate_msg_tokens = $$You have used {pct}% of your token budget, and the burn is still from re-sending context each turn. It's recoverable, but it needs a course-correction now rather than later: consolidate every remaining tool call into a single batch, stop re-reading or re-exploring, stick to the todo list, and deliver the deliverable. Re-sending less is what keeps this session alive.$$ WHERE budget_escalate_msg_tokens = $$CRITICAL: You have used {pct}% of your token budget. Your session context is too large and every turn re-sends it. STOP re-reading and exploring. Consolidate EVERY remaining tool call into a single batch, stick to your todo list, and finish the deliverable NOW. Your session will be KILLED if you keep spending at this rate.$$;
UPDATE tenant_settings SET budget_final_msg_tokens = $$You have used {pct}% of your token budget — this is the last chance before the session is stopped. Stop all exploration. Finish in the next minimal number of tool calls: batch everything, do not re-read anything already in context, and deliver the completed work now.$$ WHERE budget_final_msg_tokens = $$FINAL WARNING: You have used {pct}% of your token budget. This is your last chance. Stop all exploration. Finish your work in the next minimal number of tool calls or your session will be KILLED. Stick to your todo list and move forward efficiently. Deliver now.$$;
UPDATE tenant_settings SET budget_warn_msg_cost_usd = $$You have used {pct}% of your cost budget. Most of that is re-sent context, not new output. There's room to finish if you act now: batch the remaining tool calls into one round-trip, keep only what the task actually needs in context, and deliver the minimal delta.$$ WHERE budget_warn_msg_cost_usd = $$WARNING: You have used {pct}% of your cost budget. STOP and reconsider how you are handling context — you are re-sending too much on every turn. Stick to your todo list, consolidate your remaining tool calls into ONE batch, and deliver the minimum. Reduce your spend immediately or your session will be KILLED.$$;
UPDATE tenant_settings SET budget_escalate_msg_cost_usd = $$You have used {pct}% of your cost budget and are on pace to exceed it. Shift to the cheapest path: batch all remaining tool calls, avoid re-deriving anything already established, stick to the todo list, and finish the deliverable now.$$ WHERE budget_escalate_msg_cost_usd = $$CRITICAL: You have used {pct}% of your cost budget. You are on pace to blow past it. Use only the cheapest possible tool calls, do not re-derive anything, stick to your todo list, and finish NOW. Your session will be KILLED if you keep spending.$$;
UPDATE tenant_settings SET budget_final_msg_cost_usd = $$You have used {pct}% of your cost budget — this is the final warning. Complete the work in the next few tool calls: batch them and deliver now, or the session will be stopped.$$ WHERE budget_final_msg_cost_usd = $$FINAL WARNING: You have used {pct}% of your cost budget. This is your last warning. Complete your work in the next minimal tool calls or your session will be KILLED. Deliver now.$$;
UPDATE tenant_settings SET budget_warn_msg_tool_call_count = $$You have used {pct}% of your tool-call budget. Splitting work into many separate calls is what's consuming it — every call re-sends the whole conversation. You have room, but please batch here on: combine independent operations into ONE round-trip. Fewer, larger calls finish faster and cost less.$$ WHERE budget_warn_msg_tool_call_count = $$WARNING: YOU ARE CALLING TOOLS TOO OFTEN. STOP and batch your tool calls together into a single round-trip, stick to your todo list, and move forward efficiently — or you will risk your session being KILLED.$$;
UPDATE tenant_settings SET budget_escalate_msg_tool_call_count = $$You are at {pct}% of your tool-call budget and still making many small calls. Each one re-sends the whole conversation, which multiplies the cost. Stop the micro calls. Consolidate everything into a single round-trip and focus on completing the todo list.$$ WHERE budget_escalate_msg_tool_call_count = $$CRITICAL: YOU ARE STILL CALLING TOOLS TOO OFTEN. STOP the micro tool calls. You MUST batch them together into a single round-trip and focus on completing the todo list. Your session will be KILLED if you keep splitting your calls.$$;
UPDATE tenant_settings SET budget_final_msg_tool_call_count = $$You are at {pct}% of your tool-call budget — only a handful of calls remain. Finish in the next tool calls: batch everything into one round-trip, do not re-read, and deliver the completed work now, or the session will be stopped.$$ WHERE budget_final_msg_tool_call_count = $$FINAL WARNING: YOUR TOOL CALL LIMIT IS ALMOST REACHED. YOU HAVE ONLY A HANDFUL OF TOOL CALLS LEFT. You MUST finish your work in the next tool calls or your session WILL BE KILLED. Batch everything. Stick to the todo list. Finish now.$$;
UPDATE tenant_settings SET budget_warn_msg_wall_clock_seconds = $$You have used {pct}% of your time budget. There's still time if you move deliberately from here: batch the remaining tool calls, keep to the todo list, and finish the deliverable.$$ WHERE budget_warn_msg_wall_clock_seconds = $$WARNING: IT HAS BEEN {pct}% OF YOUR TIME BUDGET. STOP and work efficiently: batch your remaining tool calls, stick to your todo list, and finish your work to avoid exceeding budget — YOUR SESSION WILL BE KILLED.$$;
UPDATE tenant_settings SET budget_escalate_msg_wall_clock_seconds = $$You have used {pct}% of your time budget. Shift to the fastest path: batch the remaining tool calls, stop re-checking settled state, and finish now.$$ WHERE budget_escalate_msg_wall_clock_seconds = $$CRITICAL: YOU ARE RUNNING OUT OF TIME ({pct}% ELAPSED). STOP the slow path: batch your remaining tool calls, stick to your todo list, and finish NOW. Your session will be KILLED if you do not finish quickly.$$;
UPDATE tenant_settings SET budget_final_msg_wall_clock_seconds = $$You have used {pct}% of your time budget — almost out of time. Complete the work in the next tool calls and deliver now, or the session will be stopped.$$ WHERE budget_final_msg_wall_clock_seconds = $$FINAL WARNING: {pct}% OF YOUR TIME IS GONE. You have almost no time left. Complete your work in the next tool calls. Stick to your todo list. Your session will be KILLED at the time limit.$$;
