-- Work item acceptance review: a first-class, human-readable summary of
-- the final work done, auto-populated by the WorkflowReconciler when a
-- bound workflow run reaches a terminal state (docs/02 §2.2). Mirrors
-- acceptance_criteria: markdown, bounded at the API boundary, empty by
-- default. Same table -> no new RLS policy needed (row-level RLS already
-- exists).
ALTER TABLE "work_items" ADD COLUMN IF NOT EXISTS "acceptance_review" text NOT NULL DEFAULT '';
COMMENT ON COLUMN "work_items"."acceptance_review" IS 'Acceptance review: summary of the final work done, auto-generated by the WorkflowReconciler when a bound workflow run completes (docs/02 §2.2). Markdown.';
