syntax = "proto3";

package orchicon.api.v1;

import "orchicon/api/v1/secret.proto";

service SecretsService {
  rpc ListSecrets(ListSecretsRequest) returns (ListSecretsResponse);
  rpc GetSecret(GetSecretRequest) returns (GetSecretResponse);
  rpc CreateSecret(CreateSecretRequest) returns (CreateSecretResponse);
  rpc UpdateSecret(UpdateSecretRequest) returns (UpdateSecretResponse);
  rpc DeleteSecret(DeleteSecretRequest) returns (DeleteSecretResponse);
}

message ListSecretsRequest {
  string search = 1;
  int32 page_size = 2;
  string page_token = 3;
}

message ListSecretsResponse {
  repeated TenantSecret secrets = 1;
  string next_page_token = 2;
}

message GetSecretRequest {
  string id = 1;
}

message GetSecretResponse {
  TenantSecret secret = 1;
}

message CreateSecretRequest {
  string name = 1;
  string value = 2;
  string description = 3;
}

message CreateSecretResponse {
  TenantSecret secret = 1;
}

message UpdateSecretRequest {
  string id = 1;
  optional string value = 2;
  optional string description = 3;
}

message UpdateSecretResponse {
  TenantSecret secret = 1;
}

message DeleteSecretRequest {
  string id = 1;
}

message DeleteSecretResponse {}
