import type { ReactNode } from "react";
import { useEffect, useState, useRef } from "react";
import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { Layers, Sparkles, ChevronDown, LogOut, Menu, X, Moon, Sun, SlidersHorizontal, UserCog } from "lucide-react";
import { NotificationBell } from "@/components/notifications/NotificationBell";
import { cn } from "@/lib/utils";
import { useSession, logout } from "@/auth/auth";
import { setupProactiveRefreshHook, useSessionStore } from "@/auth/session";
import { useThemeStore } from "@/lib/theme-store";
import { ASK_ORCHICON, NAV_GROUPS, isPathActive, ACTIVE_TRIGGER, ACTIVE_ITEM_SUBTLE } from "@/lib/nav-config";
import { Breadcrumbs } from "@/components/breadcrumbs";
export function AppShell({ children }: { children: ReactNode }) {
  const path = useRouterState({ select: (s) => s.location.pathname });
  const isAskOrchicon = path === "/ask-orchicon" || path.startsWith("/ask-orchicon/");
  const session = useSession();
  const loading = useSessionStore((s) => s.loading);
  const navigate = useNavigate();
  useEffect(() => { setupProactiveRefreshHook(); }, []);
  useEffect(() => { if (loading || session.authenticated) return; if (path === "/login" || path === "/signup" || path === "/auth/callback") return; navigate({ to: "/login" }); }, [loading, session.authenticated, path, navigate]);
  const showBreadcrumbs = path !== "/login" && path !== "/signup" && path !== "/auth/callback" && path !== "/" && !isAskOrchicon;
  return (<div className="flex min-h-screen flex-col bg-mesh"><TopHeader /><div className="flex flex-1 overflow-hidden p-4 gap-4"><main className={cn("flex-1 min-w-0 overflow-auto flex flex-col")}><div className={cn(isAskOrchicon ? "flex-1 flex flex-col" : "flex-1 p-6 lg:p-8")}>{showBreadcrumbs && (<div className="mb-4"><Breadcrumbs /></div>)}{children}</div></main></div></div>);
}
function TopHeader() {
  const session = useSession(); const [mobileOpen, setMobileOpen] = useState(false); const [openGroup, setOpenGroup] = useState<string | null>(null); const path = useRouterState({ select: (s) => s.location.pathname }); const isAskOrchicon = isPathActive(path, ASK_ORCHICON.to); useEffect(() => { setOpenGroup(null); }, [path]);
  return (<header className="p-4 pb-0 z-50"><div className="max-w-[1920px] mx-auto glass-panel rounded-2xl px-4 py-2 flex items-center justify-between shadow-2xl gap-2"><Link to={session.authenticated ? "/ask-orchicon" : "/login"} search={session.authenticated ? { conversationId: null } as never : undefined} className="flex items-center space-x-3 pr-4 border-r border-white/10 shrink-0"><div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-cyan-500 to-indigo-500 flex items-center justify-center shadow-lg shadow-cyan-500/30 shrink-0"><Layers aria-hidden="true" className="w-5 h-5 text-white" /></div><span className="font-bold text-lg tracking-wide text-foreground hidden sm:inline">Orchicon</span></Link><nav className="hidden lg:flex items-center space-x-1 text-sm font-medium flex-1 justify-center min-w-0"><Link to={ASK_ORCHICON.to} search={{ conversationId: null } as never} aria-current={isAskOrchicon ? "page" : undefined} className={cn("flex items-center space-x-2 px-3.5 py-2 rounded-xl transition shrink-0 border border-transparent", isAskOrchicon ? ACTIVE_TRIGGER : "text-cyan-400 hover:text-cyan-300 hover:bg-cyan-500/10")}><Sparkles aria-hidden="true" className="w-4 h-4" /><span>{ASK_ORCHICON.label}</span></Link>{NAV_GROUPS.map((group) => (<DropdownGroup key={group.label} group={group} openGroup={openGroup} setOpenGroup={setOpenGroup} />))}</nav><div className="flex lg:hidden items-center ml-auto"><button onClick={() => setMobileOpen((v) => !v)} className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground" aria-label="Toggle navigation menu" aria-expanded={mobileOpen}>{mobileOpen ? <X aria-hidden="true" className="h-4 w-4" /> : <Menu aria-hidden="true" className="h-4 w-4" />}</button></div><div className="flex items-center space-x-1 sm:space-x-3 pl-4 border-l border-white/10 shrink-0">{session.authenticated ? (<><NotificationBell /><ThemeToggleInline /><AvatarBubble /></>) : (<><ThemeToggleInline /><Link to="/login" className="text-xs font-medium text-primary hover:underline px-2">Sign in</Link></>)}</div></div>{mobileOpen && <MobileDrawer open={mobileOpen} onOpenChange={setMobileOpen} />}</header>);
}
function ThemeToggleInline() { const mode = useThemeStore((s) => s.mode); const toggle = useThemeStore((s) => s.toggleMode); return (<button onClick={toggle} className="hidden sm:flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground" title={mode === "dark" ? "Switch to light mode" : "Switch to dark mode"} aria-label="Toggle theme">{mode === "dark" ? <Sun aria-hidden="true" className="h-4 w-4" /> : <Moon aria-hidden="true" className="h-4 w-4" />}</button>); }
function DropdownGroup({ group, openGroup, setOpenGroup }: { group: typeof NAV_GROUPS[number]; openGroup: string | null; setOpenGroup: (v: string | null) => void; }) {
  const isOpen = openGroup === group.label; const containerRef = useRef<HTMLDivElement>(null); const triggerRef = useRef<HTMLButtonElement>(null); const session = useSession(); const path = useRouterState({ select: (s) => s.location.pathname }); const isDomainActive = group.items.some((it) => isPathActive(path, it.to)); const visibleItems = group.items.filter((it) => !it.admin || session.is_admin); if (visibleItems.length === 0) return null;
  useEffect(() => { if (!isOpen) return; const onPointerDown = (e: PointerEvent) => { if (containerRef.current && !containerRef.current.contains(e.target as Node)) { setOpenGroup(null); } }; const onKeyDown = (e: KeyboardEvent) => { if (e.key === "Escape") { setOpenGroup(null); triggerRef.current?.focus(); } }; document.addEventListener("pointerdown", onPointerDown); document.addEventListener("keydown", onKeyDown); return () => { document.removeEventListener("pointerdown", onPointerDown); document.removeEventListener("keydown", onKeyDown); }; }, [isOpen, setOpenGroup]);
  const handleKeyDown = (e: React.KeyboardEvent) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); setOpenGroup(isOpen ? null : group.label); } else if (e.key === "ArrowDown") { e.preventDefault(); setOpenGroup(group.label); requestAnimationFrame(() => { const first = containerRef.current?.querySelector<HTMLElement>('[role="menuitem"]'); first?.focus(); }); } else if (e.key === "Escape") { setOpenGroup(null); } };
  return (<div ref={containerRef} className="relative group" data-testid={`dropdown-${group.label}`}><button ref={triggerRef} aria-haspopup="menu" aria-expanded={isOpen} aria-label={`${group.label} menu`} aria-current={isDomainActive ? "true" : undefined} onClick={() => setOpenGroup(isOpen ? null : group.label)} onKeyDown={handleKeyDown} className={cn("flex items-center space-x-1.5 px-3.5 py-2 rounded-xl transition border border-transparent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/40 focus-visible:ring-offset-0", isDomainActive ? ACTIVE_TRIGGER : "text-muted-foreground hover:text-foreground hover:bg-accent/50 hover:bg-white/5")}><span>{group.label}</span><ChevronDown aria-hidden="true" className={cn("w-3.5 h-3.5 opacity-60 transition-transform", isOpen ? "rotate-180" : "group-hover:rotate-180 group-focus-within:rotate-180")} /></button><div role="menu" aria-label={`${group.label} menu`} className={cn(group.label === "Control" ? "absolute top-full right-0 mt-2 w-52 glass-menu rounded-xl p-1.5 transition-all duration-200 transform z-50" : "absolute top-full left-0 mt-2 w-52 glass-menu rounded-xl p-1.5 transition-all duration-200 transform z-50", isOpen ? "opacity-100 visible translate-y-0" : "opacity-0 invisible translate-y-1 group-hover:opacity-100 group-hover:visible group-hover:translate-y-0 group-focus-within:opacity-100 group-focus-within:visible group-focus-within:translate-y-0")}>{visibleItems.map((item) => { const Icon = item.icon; const isItemActive = isPathActive(path, item.to); return (<Link key={item.to} to={item.to} role="menuitem" aria-current={isItemActive ? "page" : undefined} tabIndex={isOpen ? 0 : -1} onClick={() => setOpenGroup(null)} onKeyDown={(e) => { if (e.key === "ArrowDown" || e.key === "ArrowUp") { e.preventDefault(); const items = Array.from(containerRef.current?.querySelectorAll<HTMLElement>('[role="menuitem"]') ?? []); const idx = items.indexOf(e.currentTarget); const next = e.key === "ArrowDown" ? (idx + 1) % items.length : (idx - 1 + items.length) % items.length; items[next]?.focus(); } else if (e.key === "Escape") { setOpenGroup(null); triggerRef.current?.focus(); } }} className={cn("flex items-center justify-between px-3 py-2 rounded-lg transition focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/40 border border-transparent", isItemActive ? ACTIVE_ITEM_SUBTLE : "text-muted-foreground hover:text-foreground hover:bg-accent/50 hover:bg-white/10 focus:bg-white/10 focus:text-white focus-visible:text-white")}><span className="flex items-center space-x-2.5"><Icon aria-hidden="true" className={cn("w-4 h-4", item.iconColor)} /><span className="text-sm">{item.label}</span></span>{item.badge === "NEW" && <span className="text-[10px] bg-cyan-500/20 text-cyan-300 px-1.5 py-0.5 rounded border border-cyan-500/30 font-semibold">NEW</span>}</Link>); })}</div></div>);
}
function AvatarBubble() {
  const session = useSession(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); const triggerRef = useRef<HTMLButtonElement>(null); const initial = (session.username?.[0] ?? session.identity_id?.[0] ?? "A").toUpperCase(); const displayName = session.username ?? (session.identity_id ? `…${session.identity_id.slice(-8)}` : "User");
  useEffect(() => { if (!open) return; const onPointerDown = (e: PointerEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); }; const onKeyDown = (e: KeyboardEvent) => { if (e.key === "Escape") { setOpen(false); triggerRef.current?.focus(); } }; document.addEventListener("pointerdown", onPointerDown); document.addEventListener("keydown", onKeyDown); return () => { document.removeEventListener("pointerdown", onPointerDown); document.removeEventListener("keydown", onKeyDown); }; }, [open]);
  return (<div ref={ref} className="relative"><button ref={triggerRef} onClick={() => setOpen((v) => !v)} aria-haspopup="menu" aria-expanded={open} aria-label="Profile menu" className="w-7 h-7 rounded-full bg-gradient-to-r from-cyan-500 to-blue-600 flex items-center justify-center text-xs font-semibold text-white ring-2 ring-white/10 hover:ring-white/20 transition focus:outline-none focus:ring-cyan-400/50">{initial}</button><div role="menu" className={cn("absolute right-0 top-full mt-2 min-w-48 glass-menu rounded-xl p-1.5 shadow-2xl z-50 transition-all duration-200 transform", open ? "opacity-100 visible translate-y-0" : "opacity-0 invisible translate-y-1")} aria-hidden={!open}><div className="px-3 py-2 border-b border-white/10 mb-1"><p className="text-xs font-medium text-foreground truncate">{displayName}</p><p className="text-[11px] text-muted-foreground truncate">{session.is_admin ? "Administrator" : "Member"}</p></div><Link to="/settings" role="menuitem" tabIndex={open ? 0 : -1} onClick={() => setOpen(false)} className="flex items-center space-x-2.5 px-3 py-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/10 transition text-sm focus:outline-none focus:bg-white/10"><SlidersHorizontal aria-hidden="true" className="w-4 h-4 text-slate-400" /><span>Settings</span></Link>{session.is_admin && (<Link to="/admin" role="menuitem" tabIndex={open ? 0 : -1} onClick={() => setOpen(false)} className="flex items-center space-x-2.5 px-3 py-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/10 transition text-sm focus:outline-none focus:bg-white/10"><UserCog aria-hidden="true" className="w-4 h-4 text-rose-400" /><span>Admin</span></Link>)}<button role="menuitem" tabIndex={open ? 0 : -1} onClick={() => { setOpen(false); logout(); navigate({ to: "/login" }); }} className="w-full flex items-center space-x-2.5 px-3 py-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-white/10 transition text-sm focus:outline-none focus:bg-white/10 text-left"><LogOut aria-hidden="true" className="w-4 h-4 text-rose-400" /><span>Sign out</span></button></div></div>);
}
function MobileDrawer({ open, onOpenChange }: { open: boolean; onOpenChange: (v: boolean) => void }) {
  const path = useRouterState({ select: (s) => s.location.pathname }); const session = useSession();
  useEffect(() => { if (!open) return; const onKeyDown = (e: KeyboardEvent) => { if (e.key === "Escape") onOpenChange(false); }; document.addEventListener("keydown", onKeyDown); return () => document.removeEventListener("keydown", onKeyDown); }, [open, onOpenChange]);
  if (!open) return null;
  return (<div className="fixed inset-0 z-50 lg:hidden" role="dialog" aria-modal="true" aria-label="Navigation"><div className="absolute inset-0 bg-black/50" onClick={() => onOpenChange(false)} aria-hidden="true" /><div className="absolute inset-y-0 left-0 w-72 glass-menu shadow-lg overflow-y-auto flex flex-col"><div className="flex h-14 items-center justify-between gap-2 border-b border-white/10 px-5 shrink-0"><span className="flex items-center gap-2 text-lg font-semibold tracking-tight"><span className="w-7 h-7 rounded-lg bg-gradient-to-tr from-cyan-500 to-indigo-500 flex items-center justify-center"><Layers aria-hidden="true" className="w-4 h-4 text-white" /></span>Orchicon</span><button onClick={() => onOpenChange(false)} className="p-1 rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground" aria-label="Close navigation"><X aria-hidden="true" className="h-4 w-4" /></button></div><nav className="flex-1 p-3 space-y-4 overflow-y-auto"><Link to={ASK_ORCHICON.to} search={{ conversationId: null } as never} onClick={() => onOpenChange(false)} aria-current={isPathActive(path, ASK_ORCHICON.to) ? "page" : undefined} className={cn("flex items-center space-x-2.5 px-3 py-2.5 rounded-lg font-medium transition border", isPathActive(path, ASK_ORCHICON.to) ? "bg-gradient-to-r from-cyan-500/15 to-indigo-500/15 text-cyan-300 border-cyan-500/30 shadow-[0_0_12px_rgba(6,182,212,0.15)]" : "text-slate-300 hover:bg-white/10 hover:text-white border-transparent")}><Sparkles aria-hidden="true" className="w-4 h-4 text-cyan-400" /><span>{ASK_ORCHICON.label}</span></Link>{NAV_GROUPS.map((group) => { const items = group.items.filter((it) => !it.admin || session.is_admin); if (items.length === 0) return null; return (<div key={group.label}><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-500 px-3 mb-1">{group.label}</p><div className="space-y-1">{items.map((item) => { const Icon = item.icon; const active = isPathActive(path, item.to); return (<Link key={item.to} to={item.to} onClick={() => onOpenChange(false)} aria-current={active ? "page" : undefined} className={cn("flex items-center justify-between px-3 py-2 rounded-lg transition text-sm border", active ? "bg-cyan-500/15 text-cyan-300 border-cyan-500/30 shadow-[0_0_12px_rgba(6,182,212,0.12)]" : "text-slate-300 hover:bg-white/10 hover:text-white border-transparent")}><span className="flex items-center space-x-2.5"><Icon aria-hidden="true" className={cn("w-4 h-4", item.iconColor)} /><span>{item.label}</span></span>{item.badge === "NEW" && <span className="text-[10px] bg-cyan-500/20 text-cyan-300 px-1.5 py-0.5 rounded border border-cyan-500/30 font-semibold">NEW</span>}</Link>); })}</div></div>); })}</nav></div></div>);
}
