// Router setup. The route tree is generated by @tanstack/router-plugin
// (file-based, type-safe — docs/10 §2) into routeTree.gen.ts. This file
// wires the generated tree into a router instance for the provider.
import { createRouter } from "@tanstack/react-router";

import { routeTree } from "@/routeTree.gen";

export const router = createRouter({
  routeTree,
  defaultPreload: "intent",
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
