/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as WorkItemsRouteImport } from './routes/work-items'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as RuntimeImagesRouteImport } from './routes/runtime-images'
import { Route as RecurringItemsRouteImport } from './routes/recurring-items'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeaCloudRouteImport } from './routes/idea-cloud'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CostExplorerRouteImport } from './routes/cost-explorer'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as AskOrchiconRouteImport } from './routes/ask-orchicon'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsNewRouteImport } from './routes/workflows_.new'
import { Route as WorkflowsIdRouteImport } from './routes/workflows_.$id'
import { Route as WorkersNewRouteImport } from './routes/workers_.new'
import { Route as WorkersIdRouteImport } from './routes/workers_.$id'
import { Route as WorkItemsNewRouteImport } from './routes/work-items_.new'
import { Route as WorkItemsIdRouteImport } from './routes/work-items_.$id'
import { Route as RuntimeImagesNewRouteImport } from './routes/runtime-images_.new'
import { Route as RuntimeImagesIdRouteImport } from './routes/runtime-images_.$id'
import { Route as RecurringItemsNewRouteImport } from './routes/recurring-items_.new'
import { Route as RecurringItemsIdRouteImport } from './routes/recurring-items_.$id'
import { Route as RecoveryIdRouteImport } from './routes/recovery_.$id'
import { Route as ProjectsNewRouteImport } from './routes/projects_.new'
import { Route as ProjectsIdRouteImport } from './routes/projects_.$id'
import { Route as PoliciesNewRouteImport } from './routes/policies_.new'
import { Route as PoliciesIdRouteImport } from './routes/policies_.$id'
import { Route as ExecutionsIdRouteImport } from './routes/executions_.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WorkflowsIdRunsRunIdRouteImport } from './routes/workflows_.$id_.runs.$runId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsRoute = WorkItemsRouteImport.update({
  id: '/work-items',
  path: '/work-items',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeImagesRoute = RuntimeImagesRouteImport.update({
  id: '/runtime-images',
  path: '/runtime-images',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringItemsRoute = RecurringItemsRouteImport.update({
  id: '/recurring-items',
  path: '/recurring-items',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaCloudRoute = IdeaCloudRouteImport.update({
  id: '/idea-cloud',
  path: '/idea-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CostExplorerRoute = CostExplorerRouteImport.update({
  id: '/cost-explorer',
  path: '/cost-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AskOrchiconRoute = AskOrchiconRouteImport.update({
  id: '/ask-orchicon',
  path: '/ask-orchicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows_/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows_/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersNewRoute = WorkersNewRouteImport.update({
  id: '/workers_/new',
  path: '/workers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers_/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsNewRoute = WorkItemsNewRouteImport.update({
  id: '/work-items_/new',
  path: '/work-items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsIdRoute = WorkItemsIdRouteImport.update({
  id: '/work-items_/$id',
  path: '/work-items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeImagesNewRoute = RuntimeImagesNewRouteImport.update({
  id: '/runtime-images_/new',
  path: '/runtime-images/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeImagesIdRoute = RuntimeImagesIdRouteImport.update({
  id: '/runtime-images_/$id',
  path: '/runtime-images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringItemsNewRoute = RecurringItemsNewRouteImport.update({
  id: '/recurring-items_/new',
  path: '/recurring-items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringItemsIdRoute = RecurringItemsIdRouteImport.update({
  id: '/recurring-items_/$id',
  path: '/recurring-items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryIdRoute = RecoveryIdRouteImport.update({
  id: '/recovery_/$id',
  path: '/recovery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesNewRoute = PoliciesNewRouteImport.update({
  id: '/policies_/new',
  path: '/policies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIdRoute = PoliciesIdRouteImport.update({
  id: '/policies_/$id',
  path: '/policies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIdRoute = ExecutionsIdRouteImport.update({
  id: '/executions_/$id',
  path: '/executions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRunsRunIdRoute = WorkflowsIdRunsRunIdRouteImport.update({
  id: '/workflows_/$id_/runs/$runId',
  path: '/workflows/$id/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/ask-orchicon': typeof AskOrchiconRoute
  '/conversations': typeof ConversationsRoute
  '/cost-explorer': typeof CostExplorerRoute
  '/dashboard': typeof DashboardRoute
  '/executions': typeof ExecutionsRoute
  '/home': typeof HomeRoute
  '/idea-cloud': typeof IdeaCloudRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/recurring-items': typeof RecurringItemsRoute
  '/runtime-images': typeof RuntimeImagesRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/telemetry': typeof TelemetryRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/work-items': typeof WorkItemsRoute
  '/workers': typeof WorkersRoute
  '/workflows': typeof WorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/recurring-items/$id': typeof RecurringItemsIdRoute
  '/recurring-items/new': typeof RecurringItemsNewRoute
  '/runtime-images/$id': typeof RuntimeImagesIdRoute
  '/runtime-images/new': typeof RuntimeImagesNewRoute
  '/work-items/$id': typeof WorkItemsIdRoute
  '/work-items/new': typeof WorkItemsNewRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/new': typeof WorkersNewRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/ask-orchicon': typeof AskOrchiconRoute
  '/conversations': typeof ConversationsRoute
  '/cost-explorer': typeof CostExplorerRoute
  '/dashboard': typeof DashboardRoute
  '/executions': typeof ExecutionsRoute
  '/home': typeof HomeRoute
  '/idea-cloud': typeof IdeaCloudRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/recurring-items': typeof RecurringItemsRoute
  '/runtime-images': typeof RuntimeImagesRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/telemetry': typeof TelemetryRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/work-items': typeof WorkItemsRoute
  '/workers': typeof WorkersRoute
  '/workflows': typeof WorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/recurring-items/$id': typeof RecurringItemsIdRoute
  '/recurring-items/new': typeof RecurringItemsNewRoute
  '/runtime-images/$id': typeof RuntimeImagesIdRoute
  '/runtime-images/new': typeof RuntimeImagesNewRoute
  '/work-items/$id': typeof WorkItemsIdRoute
  '/work-items/new': typeof WorkItemsNewRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/new': typeof WorkersNewRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/ask-orchicon': typeof AskOrchiconRoute
  '/conversations': typeof ConversationsRoute
  '/cost-explorer': typeof CostExplorerRoute
  '/dashboard': typeof DashboardRoute
  '/executions': typeof ExecutionsRoute
  '/home': typeof HomeRoute
  '/idea-cloud': typeof IdeaCloudRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/recurring-items': typeof RecurringItemsRoute
  '/runtime-images': typeof RuntimeImagesRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/telemetry': typeof TelemetryRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/work-items': typeof WorkItemsRoute
  '/workers': typeof WorkersRoute
  '/workflows': typeof WorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/executions_/$id': typeof ExecutionsIdRoute
  '/policies_/$id': typeof PoliciesIdRoute
  '/policies_/new': typeof PoliciesNewRoute
  '/projects_/$id': typeof ProjectsIdRoute
  '/projects_/new': typeof ProjectsNewRoute
  '/recovery_/$id': typeof RecoveryIdRoute
  '/recurring-items_/$id': typeof RecurringItemsIdRoute
  '/recurring-items_/new': typeof RecurringItemsNewRoute
  '/runtime-images_/$id': typeof RuntimeImagesIdRoute
  '/runtime-images_/new': typeof RuntimeImagesNewRoute
  '/work-items_/$id': typeof WorkItemsIdRoute
  '/work-items_/new': typeof WorkItemsNewRoute
  '/workers_/$id': typeof WorkersIdRoute
  '/workers_/new': typeof WorkersNewRoute
  '/workflows_/$id': typeof WorkflowsIdRoute
  '/workflows_/new': typeof WorkflowsNewRoute
  '/workflows_/$id_/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/admin'
    | '/approvals'
    | '/ask-orchicon'
    | '/conversations'
    | '/cost-explorer'
    | '/dashboard'
    | '/executions'
    | '/home'
    | '/idea-cloud'
    | '/login'
    | '/overview'
    | '/policies'
    | '/projects'
    | '/recovery'
    | '/recurring-items'
    | '/runtime-images'
    | '/schedules'
    | '/settings'
    | '/signup'
    | '/telemetry'
    | '/usage'
    | '/webhooks'
    | '/work-items'
    | '/workers'
    | '/workflows'
    | '/auth/callback'
    | '/executions/$id'
    | '/policies/$id'
    | '/policies/new'
    | '/projects/$id'
    | '/projects/new'
    | '/recovery/$id'
    | '/recurring-items/$id'
    | '/recurring-items/new'
    | '/runtime-images/$id'
    | '/runtime-images/new'
    | '/work-items/$id'
    | '/work-items/new'
    | '/workers/$id'
    | '/workers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/workflows/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/admin'
    | '/approvals'
    | '/ask-orchicon'
    | '/conversations'
    | '/cost-explorer'
    | '/dashboard'
    | '/executions'
    | '/home'
    | '/idea-cloud'
    | '/login'
    | '/overview'
    | '/policies'
    | '/projects'
    | '/recovery'
    | '/recurring-items'
    | '/runtime-images'
    | '/schedules'
    | '/settings'
    | '/signup'
    | '/telemetry'
    | '/usage'
    | '/webhooks'
    | '/work-items'
    | '/workers'
    | '/workflows'
    | '/auth/callback'
    | '/executions/$id'
    | '/policies/$id'
    | '/policies/new'
    | '/projects/$id'
    | '/projects/new'
    | '/recovery/$id'
    | '/recurring-items/$id'
    | '/recurring-items/new'
    | '/runtime-images/$id'
    | '/runtime-images/new'
    | '/work-items/$id'
    | '/work-items/new'
    | '/workers/$id'
    | '/workers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/workflows/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/admin'
    | '/approvals'
    | '/ask-orchicon'
    | '/conversations'
    | '/cost-explorer'
    | '/dashboard'
    | '/executions'
    | '/home'
    | '/idea-cloud'
    | '/login'
    | '/overview'
    | '/policies'
    | '/projects'
    | '/recovery'
    | '/recurring-items'
    | '/runtime-images'
    | '/schedules'
    | '/settings'
    | '/signup'
    | '/telemetry'
    | '/usage'
    | '/webhooks'
    | '/work-items'
    | '/workers'
    | '/workflows'
    | '/auth/callback'
    | '/executions_/$id'
    | '/policies_/$id'
    | '/policies_/new'
    | '/projects_/$id'
    | '/projects_/new'
    | '/recovery_/$id'
    | '/recurring-items_/$id'
    | '/recurring-items_/new'
    | '/runtime-images_/$id'
    | '/runtime-images_/new'
    | '/work-items_/$id'
    | '/work-items_/new'
    | '/workers_/$id'
    | '/workers_/new'
    | '/workflows_/$id'
    | '/workflows_/new'
    | '/workflows_/$id_/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  AdminRoute: typeof AdminRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AskOrchiconRoute: typeof AskOrchiconRoute
  ConversationsRoute: typeof ConversationsRoute
  CostExplorerRoute: typeof CostExplorerRoute
  DashboardRoute: typeof DashboardRoute
  ExecutionsRoute: typeof ExecutionsRoute
  HomeRoute: typeof HomeRoute
  IdeaCloudRoute: typeof IdeaCloudRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PoliciesRoute: typeof PoliciesRoute
  ProjectsRoute: typeof ProjectsRoute
  RecoveryRoute: typeof RecoveryRoute
  RecurringItemsRoute: typeof RecurringItemsRoute
  RuntimeImagesRoute: typeof RuntimeImagesRoute
  SchedulesRoute: typeof SchedulesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TelemetryRoute: typeof TelemetryRoute
  UsageRoute: typeof UsageRoute
  WebhooksRoute: typeof WebhooksRoute
  WorkItemsRoute: typeof WorkItemsRoute
  WorkersRoute: typeof WorkersRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ExecutionsIdRoute: typeof ExecutionsIdRoute
  PoliciesIdRoute: typeof PoliciesIdRoute
  PoliciesNewRoute: typeof PoliciesNewRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  RecoveryIdRoute: typeof RecoveryIdRoute
  RecurringItemsIdRoute: typeof RecurringItemsIdRoute
  RecurringItemsNewRoute: typeof RecurringItemsNewRoute
  RuntimeImagesIdRoute: typeof RuntimeImagesIdRoute
  RuntimeImagesNewRoute: typeof RuntimeImagesNewRoute
  WorkItemsIdRoute: typeof WorkItemsIdRoute
  WorkItemsNewRoute: typeof WorkItemsNewRoute
  WorkersIdRoute: typeof WorkersIdRoute
  WorkersNewRoute: typeof WorkersNewRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  WorkflowsIdRunsRunIdRoute: typeof WorkflowsIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items': {
      id: '/work-items'
      path: '/work-items'
      fullPath: '/work-items'
      preLoaderRoute: typeof WorkItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-images': {
      id: '/runtime-images'
      path: '/runtime-images'
      fullPath: '/runtime-images'
      preLoaderRoute: typeof RuntimeImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring-items': {
      id: '/recurring-items'
      path: '/recurring-items'
      fullPath: '/recurring-items'
      preLoaderRoute: typeof RecurringItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-cloud': {
      id: '/idea-cloud'
      path: '/idea-cloud'
      fullPath: '/idea-cloud'
      preLoaderRoute: typeof IdeaCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-explorer': {
      id: '/cost-explorer'
      path: '/cost-explorer'
      fullPath: '/cost-explorer'
      preLoaderRoute: typeof CostExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-orchicon': {
      id: '/ask-orchicon'
      path: '/ask-orchicon'
      fullPath: '/ask-orchicon'
      preLoaderRoute: typeof AskOrchiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/new': {
      id: '/workflows_/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/$id': {
      id: '/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers_/new': {
      id: '/workers_/new'
      path: '/workers/new'
      fullPath: '/workers/new'
      preLoaderRoute: typeof WorkersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers_/$id': {
      id: '/workers_/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items_/new': {
      id: '/work-items_/new'
      path: '/work-items/new'
      fullPath: '/work-items/new'
      preLoaderRoute: typeof WorkItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items_/$id': {
      id: '/work-items_/$id'
      path: '/work-items/$id'
      fullPath: '/work-items/$id'
      preLoaderRoute: typeof WorkItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-images_/new': {
      id: '/runtime-images_/new'
      path: '/runtime-images/new'
      fullPath: '/runtime-images/new'
      preLoaderRoute: typeof RuntimeImagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-images_/$id': {
      id: '/runtime-images_/$id'
      path: '/runtime-images/$id'
      fullPath: '/runtime-images/$id'
      preLoaderRoute: typeof RuntimeImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring-items_/new': {
      id: '/recurring-items_/new'
      path: '/recurring-items/new'
      fullPath: '/recurring-items/new'
      preLoaderRoute: typeof RecurringItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring-items_/$id': {
      id: '/recurring-items_/$id'
      path: '/recurring-items/$id'
      fullPath: '/recurring-items/$id'
      preLoaderRoute: typeof RecurringItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery_/$id': {
      id: '/recovery_/$id'
      path: '/recovery/$id'
      fullPath: '/recovery/$id'
      preLoaderRoute: typeof RecoveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/new': {
      id: '/projects_/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id': {
      id: '/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies_/new': {
      id: '/policies_/new'
      path: '/policies/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof PoliciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies_/$id': {
      id: '/policies_/$id'
      path: '/policies/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof PoliciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions_/$id': {
      id: '/executions_/$id'
      path: '/executions/$id'
      fullPath: '/executions/$id'
      preLoaderRoute: typeof ExecutionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/$id_/runs/$runId': {
      id: '/workflows_/$id_/runs/$runId'
      path: '/workflows/$id/runs/$runId'
      fullPath: '/workflows/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowsIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  AdminRoute: AdminRoute,
  ApprovalsRoute: ApprovalsRoute,
  AskOrchiconRoute: AskOrchiconRoute,
  ConversationsRoute: ConversationsRoute,
  CostExplorerRoute: CostExplorerRoute,
  DashboardRoute: DashboardRoute,
  ExecutionsRoute: ExecutionsRoute,
  HomeRoute: HomeRoute,
  IdeaCloudRoute: IdeaCloudRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PoliciesRoute: PoliciesRoute,
  ProjectsRoute: ProjectsRoute,
  RecoveryRoute: RecoveryRoute,
  RecurringItemsRoute: RecurringItemsRoute,
  RuntimeImagesRoute: RuntimeImagesRoute,
  SchedulesRoute: SchedulesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TelemetryRoute: TelemetryRoute,
  UsageRoute: UsageRoute,
  WebhooksRoute: WebhooksRoute,
  WorkItemsRoute: WorkItemsRoute,
  WorkersRoute: WorkersRoute,
  WorkflowsRoute: WorkflowsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ExecutionsIdRoute: ExecutionsIdRoute,
  PoliciesIdRoute: PoliciesIdRoute,
  PoliciesNewRoute: PoliciesNewRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  RecoveryIdRoute: RecoveryIdRoute,
  RecurringItemsIdRoute: RecurringItemsIdRoute,
  RecurringItemsNewRoute: RecurringItemsNewRoute,
  RuntimeImagesIdRoute: RuntimeImagesIdRoute,
  RuntimeImagesNewRoute: RuntimeImagesNewRoute,
  WorkItemsIdRoute: WorkItemsIdRoute,
  WorkItemsNewRoute: WorkItemsNewRoute,
  WorkersIdRoute: WorkersIdRoute,
  WorkersNewRoute: WorkersNewRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  WorkflowsIdRunsRunIdRoute: WorkflowsIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
