/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as WorkItemsRouteImport } from './routes/work-items'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsNewRouteImport } from './routes/workflows_.new'
import { Route as WorkflowsIdRouteImport } from './routes/workflows_.$id'
import { Route as WorkersNewRouteImport } from './routes/workers_.new'
import { Route as WorkersIdRouteImport } from './routes/workers_.$id'
import { Route as WorkItemsNewRouteImport } from './routes/work-items_.new'
import { Route as WorkItemsGraphRouteImport } from './routes/work-items_.graph'
import { Route as WorkItemsIdRouteImport } from './routes/work-items_.$id'
import { Route as RecoveryIdRouteImport } from './routes/recovery_.$id'
import { Route as ProjectsNewRouteImport } from './routes/projects_.new'
import { Route as ProjectsIdRouteImport } from './routes/projects_.$id'
import { Route as PoliciesNewRouteImport } from './routes/policies_.new'
import { Route as PoliciesIdRouteImport } from './routes/policies_.$id'
import { Route as ExecutionsIdRouteImport } from './routes/executions_.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WorkflowsIdRunsRunIdRouteImport } from './routes/workflows_.$id_.runs.$runId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsRoute = WorkItemsRouteImport.update({
  id: '/work-items',
  path: '/work-items',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows_/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows_/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersNewRoute = WorkersNewRouteImport.update({
  id: '/workers_/new',
  path: '/workers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers_/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsNewRoute = WorkItemsNewRouteImport.update({
  id: '/work-items_/new',
  path: '/work-items/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsGraphRoute = WorkItemsGraphRouteImport.update({
  id: '/work-items_/graph',
  path: '/work-items/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsIdRoute = WorkItemsIdRouteImport.update({
  id: '/work-items_/$id',
  path: '/work-items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryIdRoute = RecoveryIdRouteImport.update({
  id: '/recovery_/$id',
  path: '/recovery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesNewRoute = PoliciesNewRouteImport.update({
  id: '/policies_/new',
  path: '/policies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIdRoute = PoliciesIdRouteImport.update({
  id: '/policies_/$id',
  path: '/policies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIdRoute = ExecutionsIdRouteImport.update({
  id: '/executions_/$id',
  path: '/executions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRunsRunIdRoute = WorkflowsIdRunsRunIdRouteImport.update({
  id: '/workflows_/$id_/runs/$runId',
  path: '/workflows/$id/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/admin': typeof AdminRoute
  '/executions': typeof ExecutionsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/preferences': typeof PreferencesRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/telemetry': typeof TelemetryRoute
  '/webhooks': typeof WebhooksRoute
  '/work-items': typeof WorkItemsRoute
  '/workers': typeof WorkersRoute
  '/workflows': typeof WorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/work-items/$id': typeof WorkItemsIdRoute
  '/work-items/graph': typeof WorkItemsGraphRoute
  '/work-items/new': typeof WorkItemsNewRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/new': typeof WorkersNewRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/admin': typeof AdminRoute
  '/executions': typeof ExecutionsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/preferences': typeof PreferencesRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/telemetry': typeof TelemetryRoute
  '/webhooks': typeof WebhooksRoute
  '/work-items': typeof WorkItemsRoute
  '/workers': typeof WorkersRoute
  '/workflows': typeof WorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/executions/$id': typeof ExecutionsIdRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/new': typeof PoliciesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/work-items/$id': typeof WorkItemsIdRoute
  '/work-items/graph': typeof WorkItemsGraphRoute
  '/work-items/new': typeof WorkItemsNewRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/new': typeof WorkersNewRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/admin': typeof AdminRoute
  '/executions': typeof ExecutionsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/preferences': typeof PreferencesRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/telemetry': typeof TelemetryRoute
  '/webhooks': typeof WebhooksRoute
  '/work-items': typeof WorkItemsRoute
  '/workers': typeof WorkersRoute
  '/workflows': typeof WorkflowsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/executions_/$id': typeof ExecutionsIdRoute
  '/policies_/$id': typeof PoliciesIdRoute
  '/policies_/new': typeof PoliciesNewRoute
  '/projects_/$id': typeof ProjectsIdRoute
  '/projects_/new': typeof ProjectsNewRoute
  '/recovery_/$id': typeof RecoveryIdRoute
  '/work-items_/$id': typeof WorkItemsIdRoute
  '/work-items_/graph': typeof WorkItemsGraphRoute
  '/work-items_/new': typeof WorkItemsNewRoute
  '/workers_/$id': typeof WorkersIdRoute
  '/workers_/new': typeof WorkersNewRoute
  '/workflows_/$id': typeof WorkflowsIdRoute
  '/workflows_/new': typeof WorkflowsNewRoute
  '/workflows_/$id_/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/admin'
    | '/executions'
    | '/login'
    | '/policies'
    | '/preferences'
    | '/projects'
    | '/recovery'
    | '/telemetry'
    | '/webhooks'
    | '/work-items'
    | '/workers'
    | '/workflows'
    | '/auth/callback'
    | '/executions/$id'
    | '/policies/$id'
    | '/policies/new'
    | '/projects/$id'
    | '/projects/new'
    | '/recovery/$id'
    | '/work-items/$id'
    | '/work-items/graph'
    | '/work-items/new'
    | '/workers/$id'
    | '/workers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/workflows/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/admin'
    | '/executions'
    | '/login'
    | '/policies'
    | '/preferences'
    | '/projects'
    | '/recovery'
    | '/telemetry'
    | '/webhooks'
    | '/work-items'
    | '/workers'
    | '/workflows'
    | '/auth/callback'
    | '/executions/$id'
    | '/policies/$id'
    | '/policies/new'
    | '/projects/$id'
    | '/projects/new'
    | '/recovery/$id'
    | '/work-items/$id'
    | '/work-items/graph'
    | '/work-items/new'
    | '/workers/$id'
    | '/workers/new'
    | '/workflows/$id'
    | '/workflows/new'
    | '/workflows/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/admin'
    | '/executions'
    | '/login'
    | '/policies'
    | '/preferences'
    | '/projects'
    | '/recovery'
    | '/telemetry'
    | '/webhooks'
    | '/work-items'
    | '/workers'
    | '/workflows'
    | '/auth/callback'
    | '/executions_/$id'
    | '/policies_/$id'
    | '/policies_/new'
    | '/projects_/$id'
    | '/projects_/new'
    | '/recovery_/$id'
    | '/work-items_/$id'
    | '/work-items_/graph'
    | '/work-items_/new'
    | '/workers_/$id'
    | '/workers_/new'
    | '/workflows_/$id'
    | '/workflows_/new'
    | '/workflows_/$id_/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  AdminRoute: typeof AdminRoute
  ExecutionsRoute: typeof ExecutionsRoute
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRoute
  PreferencesRoute: typeof PreferencesRoute
  ProjectsRoute: typeof ProjectsRoute
  RecoveryRoute: typeof RecoveryRoute
  TelemetryRoute: typeof TelemetryRoute
  WebhooksRoute: typeof WebhooksRoute
  WorkItemsRoute: typeof WorkItemsRoute
  WorkersRoute: typeof WorkersRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ExecutionsIdRoute: typeof ExecutionsIdRoute
  PoliciesIdRoute: typeof PoliciesIdRoute
  PoliciesNewRoute: typeof PoliciesNewRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  RecoveryIdRoute: typeof RecoveryIdRoute
  WorkItemsIdRoute: typeof WorkItemsIdRoute
  WorkItemsGraphRoute: typeof WorkItemsGraphRoute
  WorkItemsNewRoute: typeof WorkItemsNewRoute
  WorkersIdRoute: typeof WorkersIdRoute
  WorkersNewRoute: typeof WorkersNewRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  WorkflowsIdRunsRunIdRoute: typeof WorkflowsIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items': {
      id: '/work-items'
      path: '/work-items'
      fullPath: '/work-items'
      preLoaderRoute: typeof WorkItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/new': {
      id: '/workflows_/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/$id': {
      id: '/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers_/new': {
      id: '/workers_/new'
      path: '/workers/new'
      fullPath: '/workers/new'
      preLoaderRoute: typeof WorkersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers_/$id': {
      id: '/workers_/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items_/new': {
      id: '/work-items_/new'
      path: '/work-items/new'
      fullPath: '/work-items/new'
      preLoaderRoute: typeof WorkItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items_/graph': {
      id: '/work-items_/graph'
      path: '/work-items/graph'
      fullPath: '/work-items/graph'
      preLoaderRoute: typeof WorkItemsGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items_/$id': {
      id: '/work-items_/$id'
      path: '/work-items/$id'
      fullPath: '/work-items/$id'
      preLoaderRoute: typeof WorkItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery_/$id': {
      id: '/recovery_/$id'
      path: '/recovery/$id'
      fullPath: '/recovery/$id'
      preLoaderRoute: typeof RecoveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/new': {
      id: '/projects_/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id': {
      id: '/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies_/new': {
      id: '/policies_/new'
      path: '/policies/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof PoliciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies_/$id': {
      id: '/policies_/$id'
      path: '/policies/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof PoliciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions_/$id': {
      id: '/executions_/$id'
      path: '/executions/$id'
      fullPath: '/executions/$id'
      preLoaderRoute: typeof ExecutionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/$id_/runs/$runId': {
      id: '/workflows_/$id_/runs/$runId'
      path: '/workflows/$id/runs/$runId'
      fullPath: '/workflows/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowsIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  AdminRoute: AdminRoute,
  ExecutionsRoute: ExecutionsRoute,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRoute,
  PreferencesRoute: PreferencesRoute,
  ProjectsRoute: ProjectsRoute,
  RecoveryRoute: RecoveryRoute,
  TelemetryRoute: TelemetryRoute,
  WebhooksRoute: WebhooksRoute,
  WorkItemsRoute: WorkItemsRoute,
  WorkersRoute: WorkersRoute,
  WorkflowsRoute: WorkflowsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ExecutionsIdRoute: ExecutionsIdRoute,
  PoliciesIdRoute: PoliciesIdRoute,
  PoliciesNewRoute: PoliciesNewRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  RecoveryIdRoute: RecoveryIdRoute,
  WorkItemsIdRoute: WorkItemsIdRoute,
  WorkItemsGraphRoute: WorkItemsGraphRoute,
  WorkItemsNewRoute: WorkItemsNewRoute,
  WorkersIdRoute: WorkersIdRoute,
  WorkersNewRoute: WorkersNewRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  WorkflowsIdRunsRunIdRoute: WorkflowsIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
