package aigateway

import (
	"context"
	"log/slog"
	"time"

	apiv1 "github.com/beardedparrott/orchicon/api/gen/go/orchicon/api/v1"
	"github.com/beardedparrott/orchicon/internal/db"
)

// UsageRecorder records LLM usage: Postgres (source of truth) + OTel
// metrics (VictoriaMetrics half of the dual-write). The opencode adapter
// calls Record on each step_finish event carrying tokens + cost
// (docs/04 §6.1, docs/08 §5.2).
//
// Usage recording never blocks the execution path: a DB error is logged
// and the row is dropped from Postgres (the OTel metric still emits).
// Telemetry loss never corrupts control state (docs/08 §8 invariant #5).
// PricingResolver resolves catalog pricing for a provider/model. It returns
// (cost, true) when the catalog carries authoritative pricing for the model;
// (nil, false) when it is absent so the caller falls back to the
// adapter-reported cost. Matching is provider/model-aware and case-insensitive.
type PricingResolver func(ctx context.Context, provider, model string) (*apiv1.ModelCost, bool)

type UsageRecorder struct {
	pool    *db.Pool
	log     *slog.Logger
	metrics *usageMetrics
	pricing PricingResolver
}

// NewUsageRecorder constructs a UsageRecorder.
func NewUsageRecorder(pool *db.Pool, log *slog.Logger) *UsageRecorder {
	return &UsageRecorder{pool: pool, log: log, metrics: newUsageMetrics(log)}
}

// SetPricingResolver injects the catalog pricing resolver. When set, Record
// computes CostUSD from catalog pricing (authoritative, incl. $0 free models)
// instead of trusting the adapter-reported cost verbatim. A nil resolver (or
// a resolver miss) leaves the adapter-reported cost authoritative.
func (u *UsageRecorder) SetPricingResolver(fn PricingResolver) { u.pricing = fn }

// UsageInput is the usage sample from an adapter telemetry event
// (docs/04 §6.1 step_finish carries tokens + cost). It is the canonical,
// provider-agnostic shape every adapter normalizes into before the gateway
// records it — the gateway never branches on provider.
//
// Token buckets (docs §canonical-usage-sample-contract):
//   - PromptTokens     brand-new input tokens (not served from cache)
//   - CacheReadTokens  prompt tokens served from an existing cache entry
//   - CacheWriteTokens prompt tokens newly stored to cache (create/save)
//   - CompletionTokens model-generated output tokens
//   - ReasoningTokens  OPTIONAL sub-bucket of CompletionTokens (not additive)
//
// TotalTokens is NOT carried here: it is derived by UsageRecorder.Record as
// the four-bucket sum (Prompt+CacheRead+CacheWrite+Completion). Reasoning is
// deliberately excluded — providers that report it separately bill it as
// output, so adding it would double-count.
type UsageInput struct {
	TenantID         string
	ProjectID        string
	TaskID           string
	ExecutionID      string
	WorkerID         string
	Provider         string
	Model            string
	PromptTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	CompletionTokens int64
	ReasoningTokens  int64
	CostUSD          float64
	CorrelationID    string
	TraceID          string
	WorkflowRunID    string
}

// Record performs the dual-write: inserts a usage_records row in Postgres
// (in its own transaction — usage is recorded outside the execution's
// state transaction to avoid coupling telemetry to control state) and
// emits the OTel metrics that mirror it to VictoriaMetrics (docs/08 §1, §5.2).
// Returns the persisted row. The ID is generated by the data-access layer.
func (u *UsageRecorder) Record(ctx context.Context, in UsageInput) (db.UsageRecordRow, error) {
	row := db.UsageRecordRow{
		TenantID:         in.TenantID,
		ProjectID:        in.ProjectID,
		TaskID:           in.TaskID,
		ExecutionID:      in.ExecutionID,
		WorkerID:         in.WorkerID,
		Provider:         in.Provider,
		Model:            in.Model,
		PromptTokens:     in.PromptTokens,
		CacheReadTokens:  in.CacheReadTokens,
		CacheWriteTokens: in.CacheWriteTokens,
		CompletionTokens: in.CompletionTokens,
		ReasoningTokens:  in.ReasoningTokens,
		TotalTokens:      in.PromptTokens + in.CacheReadTokens + in.CacheWriteTokens + in.CompletionTokens,
		CostUSD:          in.CostUSD,
		CorrelationID:    in.CorrelationID,
		TraceID:          in.TraceID,
		OccurredAt:       time.Now().UTC(),
		CreatedAt:        time.Now().UTC(),
		WorkflowRunID:    in.WorkflowRunID,
	}

	// Cost authority: if a pricing resolver is wired, the catalog price is
	// authoritative — even when it is $0 (a genuinely free model). The
	// adapter-reported cost is the fallback when the model is unmatched or the
	// catalog carries no pricing, so the recorded cost never regresses and a
	// free model is never billed by an adapter-reported nonzero. A resolver
	// error never fails the record: the adapter cost stands.
	//
	// The resolver runs on a context detached from the caller so a cancelled
	// request does not short-circuit the telemetry write.
	if u.pricing != nil {
		cost, ok := u.pricing(context.WithoutCancel(ctx), in.Provider, in.Model)
		if ok && cost != nil {
			if p, ok := usageCostFromCatalog(in, cost); ok {
				in.CostUSD = p
				row.CostUSD = p
				u.log.Debug("usage cost from catalog", "source", "catalog", "provider", in.Provider, "model", in.Model, "costUSD", p)
			}
		} else {
			u.log.Debug("usage cost from adapter", "source", "adapter", "provider", in.Provider, "model", in.Model, "costUSD", in.CostUSD)
		}
	}

	// Postgres write (source of truth). Own transaction — usage is
	// independent of the execution's state mutations (docs/08 §1).
	if u.pool != nil && in.TenantID != "" {
		ttx, err := u.pool.BeginTenantTx(ctx, in.TenantID)
		if err != nil {
			u.log.Warn("usage record: begin tx failed", "error", err)
		} else {
			persisted, err := db.CreateUsageRecord(ctx, ttx.Tx, row)
			// Commit the transaction so the row sticks. The previous
			// version called ttx.Rollback here unconditionally — which
			// silently dropped every usage record — so usage_records
			// stayed empty even when the model was clearly running and
			// the AI Gateway was wired up. (Same pattern as the
			// recovery / opencode fixes in PR #69 / #70: a one-liner
			// that disables the whole feature.)
			if err != nil {
				_ = ttx.Rollback(ctx)
				u.log.Warn("usage record: insert failed (telemetry-only)", "error", err)
			} else {
				if err := ttx.Commit(ctx); err != nil {
					u.log.Warn("usage record: commit failed", "error", err)
				}
				row = persisted
			}
		}
	}

	// OTel metrics (VictoriaMetrics half of the dual-write). Best-effort.
	u.metrics.emit(ctx, &row)

	return row, nil
}
