package aigateway

import (
	"context"
	"log/slog"
	"time"

	"github.com/beardedparrott/orchicon/internal/db"
)

// UsageRecorder records LLM usage: Postgres (source of truth) + OTel
// metrics (ClickHouse half of the dual-write). The opencode adapter
// calls Record on each step_finish event carrying tokens + cost
// (docs/04 §6.1, docs/08 §5.2).
//
// Usage recording never blocks the execution path: a DB error is logged
// and the row is dropped from Postgres (the OTel metric still emits).
// Telemetry loss never corrupts control state (docs/08 §8 invariant #5).
type UsageRecorder struct {
	pool    *db.Pool
	log     *slog.Logger
	metrics *usageMetrics
}

// NewUsageRecorder constructs a UsageRecorder.
func NewUsageRecorder(pool *db.Pool, log *slog.Logger) *UsageRecorder {
	return &UsageRecorder{pool: pool, log: log, metrics: newUsageMetrics(log)}
}

// UsageInput is the usage sample from an adapter telemetry event
// (docs/04 §6.1 step_finish carries tokens + cost).
type UsageInput struct {
	TenantID         string
	ProjectID        string
	TaskID           string
	ExecutionID      string
	WorkerID         string
	Provider         string
	Model            string
	PromptTokens     int64
	CompletionTokens int64
	CostUSD          float64
	CorrelationID    string
	TraceID          string
}

// Record performs the dual-write: inserts a usage_records row in Postgres
// (in its own transaction — usage is recorded outside the execution's
// state transaction to avoid coupling telemetry to control state) and
// emits the OTel metrics that mirror it to ClickHouse (docs/08 §1, §5.2).
// Returns the persisted row. The ID is generated by the data-access layer.
func (u *UsageRecorder) Record(ctx context.Context, in UsageInput) (db.UsageRecordRow, error) {
	row := db.UsageRecordRow{
		TenantID:         in.TenantID,
		ProjectID:        in.ProjectID,
		TaskID:           in.TaskID,
		ExecutionID:      in.ExecutionID,
		WorkerID:         in.WorkerID,
		Provider:         in.Provider,
		Model:            in.Model,
		PromptTokens:     in.PromptTokens,
		CompletionTokens: in.CompletionTokens,
		TotalTokens:      in.PromptTokens + in.CompletionTokens,
		CostUSD:          in.CostUSD,
		CorrelationID:    in.CorrelationID,
		TraceID:          in.TraceID,
		OccurredAt:       time.Now().UTC(),
		CreatedAt:        time.Now().UTC(),
	}

	// Postgres write (source of truth). Own transaction — usage is
	// independent of the execution's state mutations (docs/08 §1).
	if u.pool != nil && in.TenantID != "" {
		ttx, err := u.pool.BeginTenantTx(ctx, in.TenantID)
		if err != nil {
			u.log.Warn("usage record: begin tx failed", "error", err)
		} else {
			persisted, err := db.CreateUsageRecord(ctx, ttx.Tx, row)
			// Commit the transaction so the row sticks. The previous
			// version called ttx.Rollback here unconditionally — which
			// silently dropped every usage record — so usage_records
			// stayed empty even when the model was clearly running and
			// the AI Gateway was wired up. (Same pattern as the
			// recovery / opencode fixes in PR #69 / #70: a one-liner
			// that disables the whole feature.)
			if err != nil {
				_ = ttx.Rollback(ctx)
				u.log.Warn("usage record: insert failed (telemetry-only)", "error", err)
			} else {
				if err := ttx.Commit(ctx); err != nil {
					u.log.Warn("usage record: commit failed", "error", err)
				}
				row = persisted
			}
		}
	}

	// OTel metrics (ClickHouse half of the dual-write). Best-effort.
	u.metrics.emit(ctx, &row)

	return row, nil
}
